name: Build-actsvg+Python
on: [push]
jobs:
  build-actsvg-run-python:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: checkout all the submodulesz
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Build actSVG + Install Dependencies + Run Scripts
        run: |
          cmake -S extern/actsvg -B extern/actsvg_build -DCMAKE_INSTALL_PREFIX="extern/actsvg_installed" \
          -DACTSVG_BUILD_TESTING=OFF -DACTSVG_BUILD_PYTHON_BINDINGS=On -DACTSVG_BUILD_EXAMPLES=OFF \
          -DCMAKE_CXX_STANDARD=17
          cmake --build extern/actsvg_build --target install
          python -m pip install --upgrade pip numpy 
          source extern/actsvg_installed/python/setup.sh
          wget https://root.cern/download/root_v6.32.04.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz
          tar xf root_v6.32.04.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz
          source root/bin/thisroot.sh
          python src/preview.py
          python src/load_sensitives.py
