name: Build-actsvg+Python
on: [push]
jobs:
  build-actsvg-run-python:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout all the submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Build actsvg + Install Dependencies + Run Scripts
        run: |
          cmake -S extern/actsvg -B extern/actsvg_build -DCMAKE_INSTALL_PREFIX="extern/actsvg_installed" \
          -DACTSVG_BUILD_TESTING=OFF -DACTSVG_BUILD_PYTHON_BINDINGS=On -DACTSVG_BUILD_EXAMPLES=OFF \
          -DCMAKE_CXX_STANDARD=17
          cmake --build extern/actsvg_build --target install
          python -m pip install --upgrade pip numpy uproot
          source extern/actsvg_installed/python/setup.sh
          sudo apt-get install binutils cmake dpkg-dev g++ gcc libssl-dev git libx11-dev \
          libxext-dev libxft-dev libxpm-dev python3 libtbb-dev libvdt-dev
          wget https://root.cern/download/root_v6.32.04.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz
          tar xf root_v6.32.04.Linux-ubuntu24.04-x86_64-gcc13.2.tar.gz
          source root/bin/thisroot.sh
          python src/preview.py
          python src/load_sensitives.py
          echo "Same step:"
          ls
      - name: ls after run
        run: |
          ls
