name: Build-actsvg+Python
on: [push]
jobs:
  build-actsvg-run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: checkout all the submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build actsvg
        working-directory: extern
        run: |
          cmake -S actsvg -B actsvg_build -DCMAKE_INSTALL_PREFIX="actsvg_installed" \
          -DACTSVG_BUILD_TESTING=OFF -DACTSVG_BUILD_PYTHON_BINDINGS=On -DACTSVG_BUILD_EXAMPLES=OFF \
          -DCMAKE_CXX_STANDARD=17
          cmake --build actsvg_build --target install
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Python Modules
        run: |
          python -m pip install --upgrade pip numpy 
          conda install conda-forge root
      - name: Source setup
        run: |
          source extern/actsvg_installed/python/setup.sh
      - name: Run python scripts
        run: |
          python src/preview.py
          python src/load_sensitives.py
      
